### ISSUE TITLE
TODO: Clean up the code 

### ISSUE THREAD

**Issue by rTonyCloud** [rTonyCloud/Professional-Portfolio#1]
- [ ] Clean the code by refactoring plain texts, styles inside double brackets

- [ ] 1. Refactor texts by replacing them with new map and importing into src/pages/portfolio/* 
- [ ] 2. Refactor reusable components and clean up texts, styling and etc
- [ ] 3. Refactor homepage code with responsive design 
- [ ] 4. Fix the Image, resizing and errors
- [ ] 5. Fix rtonycloud block with images and texts not being submerged.
- [ ] 6. Make the carousel from scratch 
- [ ] 7. Fix the block for company with responsive design
- [ ] 8. Add more reviews
